server:
  port: 41
camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: admin
  filter:
    create: All tasks
  application:
        delete-upon-undeploy: false
        scan-for-process-definitions: false
        deploy-changed-only: true
        resume-previous-versions: true
        resume-previous-by: a value
  job-execution:
        enabled: true
  metrics:
        enabled: false
        db-reporter-activate: false
